import { PROMISE } from '../content';

const FACTS = [
  { k: `From ${PROMISE.lowestPerLook}`, v: 'per finished look' },
  { k: PROMISE.turnaround, v: 'from garment to full set' },
  { k: '4K + 9:16', v: 'stills and reels together' },
  { k: 'No reshoot fee', v: 'revise until it is right' },
];

export default function Hero() {
  return (
    <section className="hero" id="top">
      <div className="wrap hero-inner">
        <div className="hero-copy">
          <p className="eyebrow">Wakubo — fashion production studio</p>

          <h1>
            Every garment you make,
            <br />
            shot like a <em>campaign</em>.
          </h1>

          <p className="lede">
            Send us the piece. We send back a full set of model photographs and
            motion — the quality your collection deserves, at a fraction of what
            a studio day costs, in {PROMISE.turnaround}.
          </p>

          <div className="hero-ctas">
            <a href="#start" className="btn btn-solid">
              Get one look free
            </a>
            <a href="#work" className="btn">
              See the output
            </a>
          </div>

          <p className="hero-note">
            No studio rental · No model day-rate · No crew · No reshoot fees
          </p>
        </div>

        <figure className="hero-visual">
          <div className="frame frame-tall">
            <video
              src="/media/motion-stand.mp4"
              poster="/media/motion-stand.webp"
              autoPlay
              muted
              loop
              playsInline
              preload="metadata"
              aria-label="Model wearing a knitted polo and wide-leg trousers, generated by Wakubo"
            />
            <span className="tag">Generated · not photographed</span>
          </div>
          <figcaption className="frame-cap">
            <span>
              <b>1</b> flat lay in
            </span>
            <span>
              <b>7</b> stills · <b>4</b> reels out
            </span>
          </figcaption>
        </figure>
      </div>

      <div className="wrap">
        <ul className="fact-strip">
          {FACTS.map((f) => (
            <li key={f.k}>
              <b>{f.k}</b>
              <span>{f.v}</span>
            </li>
          ))}
        </ul>
      </div>
    </section>
  );
}
